### ISSUE TITLE
SSL apache configuration failing on installation at InsertContent

### ISSUE THREAD

**Issue by acheckley** [kaltura/platform-install-packages#367]
Hi Everyone,

I had problems installing the latest version of Kaltura (Centos 6.5 Minimal) so rolled back to 10.7.

Version 10.7 http install works perfectly.

The httpS installation fails at the InsertContent stage.

Upon checking the virtual host files, the kaltura.conf only contains template locations. Both the kaltura.ssl.conf and the kaltura.conf substitute in double port numbers e.g. */443:433 and https://mysite.com:443:433.

I've followed the prompts on the install to no avail and had greater success commenting out the http configuration and entering my own values manually or by pre-populating the kaltura.conf.template and running the script. I've then had to go in and delete the double ports. 

Thanks,

Andrew

**Comment by acheckley** [comment]
My information:

TIME_ZONE="Europe/London"
KALTURA_FULL_VIRTUAL_HOST_NAME="mediaserver.company.co.uk:443"
KALTURA_VIRTUAL_HOST_NAME="mediaserver.company.co.uk"
DB1_HOST="127.0.0.1"
DB1_PORT="3306"
DB1_PASS="REMOVED"
DB1_NAME="kaltura"
DB1_USER="kaltura"
SERVICE_URL="https://mediaserver.company.co.uk:443"
SPHINX_SERVER1="127.0.0.1"
SPHINX_SERVER2=" "
DWH_HOST="127.0.0.1"
DWH_PORT="3306"
SPHINX_DB_HOST="127.0.0.1"
SPHINX_DB_PORT="3306"
ADMIN_CONSOLE_ADMIN_MAIL="REMOVED"
ADMIN_CONSOLE_PASSWORD="REMOVED"
CDN_HOST="mediaserver.company.co.uk"
KALTURA_VIRTUAL_HOST_PORT="443"
SUPER_USER="root"
SUPER_USER_PASSWD="REMOVED"
ENVIRONMENT_NAME="Kaltura Video Platform"
DWH_PASS="REMOVED"
PROTOCOL="https"
RED5_HOST="mediaserver.company.co.uk"
USER_CONSENT="0"
CONTACT_MAIL="NO"
VOD_PACKAGER_HOST="mediaserver.company.co.uk"
VOD_PACKAGER_PORT="88"
IP_RANGE="0.0.0.0-255.255.255.255"

php -v 
PHP 5.3.3

Configured yum proxy, user proxy and no_proxy locations
Disabled CURL SSL check (for testing)

curl -I -v $SERVICE_URL/kmc
curl -I -v $SERVICE_URL/api_v3/

apachectl -t -DDUMP_VHOSTS
VirtualHost configuration:
127.0.0.1:443          mediaserver.company.co.uk (/etc/httpd/conf.d/zzzkaltura.ssl.conf:17)
10.9.3.1:443         mediaserver.company.co.uk (/etc/httpd/conf.d/zzzkaltura.ssl.conf:17)
wildcard NameVirtualHosts and _default_ servers:
_default_:443          mediaserver.company.co.uk (/etc/httpd/conf.d/ssl.conf:74)
*:80                   mediaserver.company.co.uk (/etc/httpd/conf.d/zzzkaltura.conf:1)
Syntax OK

**Comment by jessp01** [comment]
Hi Andrew,

You are right, this is indeed a bug. Please edit the template file:
/opt/kaltura/app/configurations/apache/kaltura.ssl.conf.template

And remove:
':@KALTURA_VIRTUAL_HOST_PORT@'
It should work then. And we will have it fixed in our repos shortly.

This is actually a fix that needs to happen here:
https://github.com/kaltura/server/blob/master/configurations/apache/kaltura.ssl.conf.template

If you'd like to submit a pull request then we can also credit you for the finding.

Thanks,

**Comment by acheckley** [comment]
. /etc/profile.d/kaltura_base.sh

kaltlog

[Wed Apr 01 15:34:22 2015] [error] [client 10.9.4.174] File does not exist: /opt/kaltura/app/alpha/web/opt, referer: https://mediaserver.company.co.uk/admin_console/index.php/user/login
[Wed Apr 01 15:47:42 2015] [error] [client 10.9.4.174] File does not exist: /opt/kaltura/app/alpha/web/opt, referer: https://mediaserver.company.co.uk/admin_console/index.php/user/login

--
[2015-04-01 15:23:45]failed to connect [1] [0.0042300224304199] mysql:host=127.0.0.1;port=3306;dbname=kaltura_sphinx_log;
PHP Fatal error:  Uncaught exception 'PropelException' with message 'Unable to open PDO connection dsn[mysql:host=127.0.0.1;port=3306;dbname=kaltura_sphinx_log;] user[kaltura] password[REMOVED] [wrapped: SQLSTATE[42000] [1044] Access denied for user 'kaltura'@'%' to database 'kaltura_sphinx_log']' in /opt/kaltura/app/vendor/propel/Propel.php:649
Stack trace:
#0 /opt/kaltura/app/vendor/propel/Propel.php(532): Propel::initConnection(Array, 'sphinx_log')
--
2015-04-01 15:40:15 [0.006070] [127.0.0.1] [1841975520] [PS2] [sfView->initialize] INFO: {sfView} initialize view for "kmc/kmc"
2015-04-01 15:40:15 [0.012586] [127.0.0.1] [1841975520] [PS2] [sfPHPView->renderFile] INFO: {sfView} render "/opt/kaltura/app/alpha/apps/kaltura/modules/kmc/templates/kmcSuccess.php"
2015-04-01 15:40:15 [0.006206] [127.0.0.1] [1841975520] [PS2] [sfPHPView->decorate] INFO: {sfView} decorate content with "/opt/kaltura/app/alpha/apps/kaltura/templates/kmclayout.php"
2015-04-01 15:40:15 [0.000210] [127.0.0.1] [1841975520] [PS2] [sfPHPView->renderFile] INFO: {sfView} render "/opt/kaltura/app/alpha/apps/kaltura/templates/kmclayout.php"
2015-04-01 15:40:15 [0.003094] [127.0.0.1] [1841975520] [PS2] [sfRenderingFilter->execute] INFO: {sfFilter} render to client
--
2015-04-01 15:26:09 [1512025366] [addPermissionsAndItems.php] [addItemToPermissions] ALERT: exception 'Exception' with message 'ERROR - Permission name [] for partner [0] not found in database - skipping!' in /opt/kaltura/app/infra/log/KalturaLog.php:64
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/utils/permissions/addPermissionsAndItems.php(280): KalturaLog::alert('ERROR - Permiss...')

**Comment by acheckley** [comment]
Thanks Jess

**Comment by jessp01** [comment]
Hi,

Your DB obviously is corrupted cause of the SSL bug.
Please remove it using kaltura-drop-db.sh and then rerun config scripts 
post editing the template.

Thanks,

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by acheckley** [comment]
Hi Jess,

I've re-run the scripts and still get a fail. 

Reloading httpd: not reloading due to configuration syntax error
                                                           [FAILED]

I suspect I know what is causing this though and will complete a few checks before adding a new comment.

**Comment by acheckley** [comment]
I've since updated my original ssl.conf from the httpd/conf.d and changed the location of my server .crt and .key file.

This enables me to restart apache successfully and access the web address. The crt and key file are password protected.

When logging in, I obtain the error:

An error occurred
(error code: API:-1)

**Comment by acheckley** [comment]
/opt/kaltura/bin/kaltura-sanity.sh

[root@sslkaltura apache]# /opt/kaltura/bin/kaltura-sanity.sh
[Space on /] [PASSED, RC: 0] - [.017042416]
[Space on /opt/kaltura/web] [PASSED, RC: 0] - [.006991343]
[Check httpd daemon status] [PASSED, RC: 0] - [.058751729]

Lots of:

Napping 1 seconds to allow the daemon httpd to finish its init after monit restarted it..

[Check httpd daemon is started by Monit] [FAILED, RC: 1] - [63.161998757]
[check daemon httpd init status] [PASSED, RC: 0] - [.012274550]
[Check kaltura-sphinx daemon status] [PASSED, RC: 0] - [.060774872]

Lots of:

Napping 1 seconds to allow the daemon kaltura-sphinx to finish its init after monit restarted it..

[Check kaltura-sphinx daemon is started by Monit] [PASSED, RC: 0] - [14.265003346]
[check daemon kaltura-sphinx init status] [PASSED, RC: 0] - [.012946260]
[Check kaltura-batch daemon status] [PASSED, RC: 0] - [.052796706]

Lots of:

Napping 1 seconds to allow the daemon kaltura-batch to finish its init after monit restarted it..

[check daemon kaltura-batch init status] [PASSED, RC: 0] - [.008007310]
[Check kaltura-monit daemon status] [PASSED, RC: 0] - [.032170574]
[check daemon kaltura-monit init status] [PASSED, RC: 0] - [.007274321]
[Check memcached daemon status] [PASSED, RC: 0] - [.032510921]

Lots of:

Napping 1 seconds to allow the daemon memcached to finish its init after monit restarted it..

[Check memcached daemon is started by Monit] [PASSED, RC: 0] - [7.403934970]
[check daemon memcached init status] [PASSED, RC: 0] - [.008878114]
[kaltura-html5lib ver in KMC config.ini] [PASSED, RC: 0] - [.107392621]
[kaltura-kdp3 ver in KDP3 config.ini] [PASSED, RC: 0] - [.061064003]
[kaltura-kmc ver in KMC config.ini] [PASSED, RC: 0] - [.068689764]

PHP Warning:  file_get_contents(https://mediaserver.company.co.uk:443/kmc): failed to open stream: Connection refused in /opt/kaltura/bin/get_kmc_swfs.php on line 9

[Get KMC SWFs] [FAILED, RC: 255] - [.165930357]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[check_testme_page] [FAILED, RC: 1] - [.015415737]
[check_kmc_index_page] [FAILED, RC: 1] - [.009138663]
curl: no URL specified!
curl: try 'curl --help' or 'curl --manual' for more information
[check_admin_console_index_page] [FAILED, RC: 1] - [.016394777]
[check_studio_index_page] [FAILED, RC: 1] - [.459806752]
[check_clipapp_index_page] [FAILED, RC: 1] - [.454949475]
[Create Partner] [FAILED, RC: 255] - [.150973172]
Partner creation failed. I will skip all tests that require it.
[Red5 file upload] [SKIPPED as OflaDemo isn't configured]
see: https://github.com/kaltura/platform-install-packages/blob/master/doc/install-kaltura-redhat-based.md#configure-red5-server

Thank you for running Kaltura! To keep Kaltura viable, stable and well tested, please join the community and help by contributing sanity tests that verify overall platform stability: http://bit.ly/kaltura-ci , and by contributing to the project roadmap by solving simple tasks and challenges: http://bit.ly/kaltura-tasks.

**Comment by jessp01** [comment]
Hello,

Not sure I understand the current situation.. just to confirm:
0. dropped the db
1. edited the template for ssl conf and removed the @KALTURA_VIRTUAL_HOST_PORT@ token
2. re-run the kaltura-config-all.sh script

and the tokens were not replaced?

Thanks,

**Comment by acheckley** [comment]
Correct.

Tokens were not replaced in /configurations/apache/conf.d/zzzkaltura.conf

and this interfered with the installation.

**Comment by acheckley** [comment]
Thanks Jess. If I re-run /opt/kaltura/bin/kaltura-config-all.sh

A new answer file will be generated. Is there a method of using a previous answer file to configure Kaltura?

**Comment by jessp01** [comment]
Yes, you can put it anywhere you'd like and pass it as an argument to the 
config scripts.

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by acheckley** [comment]
Great, I've just ran a complete fresh install and the https isn't appearing as an issue on a fresh installation (only a re-installation over the top of the old installation). I'm going to double check and see if I can identify any errors on the initial installation by cloning my fresh VB and re-running the installation. (I'll have a clean log).

I'll email the log over to you.

**Comment by jessp01** [comment]
Great. So first, can you please submit a pull request to fix:
https://github.com/kaltura/server/blob/Jupiter-10.8.0/configurations/apache/kaltura.ssl.conf.template

As per our discussion? I would like for the report to be attributed to 
you. If you prefer, I can submit the pull myself and just link to the 
issue you opened, whichever way you feel like, just let me know.

Next, I would like to find the reason why a reconfig fails for you as it 
SHOULD be supported so please send me the log.

Thanks a lot,

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by acheckley** [comment]
Thanks Jess, I have created a pull request:

https://github.com/kaltura/server/compare/Jupiter-10.8.0...acheckley:patch-1

https://github.com/kaltura/server/pull/2384/files

**Comment by acheckley** [comment]
For reference, the output of the SSL script is as follows:

Generating client libs...
This can take a few minutes to complete, see log at /opt/kaltura/log/generate.php.log.

        Configuration of 10.7.0 finished successfully!
Running FrontEnd config...


base-config completed successfully, if you ever want to re-configure your system (e.g. change DB hostname) run the following script:
# rm /opt/kaltura/app/base-config.lock
# /opt/kaltura/bin/kaltura-base-config.sh


kaltura-front-10.7.0-1.noarch
Is your Apache working with SSL?[Y/n]
y
Please input path to your SSL certificate[/etc/ssl/certs/localhost.crt]:
/etc/ssl/certs/server.crt
Please input path to your SSL key[/etc/pki/tls/private/localhost.key]:
/etc/pki/tls/private/server.key
Please input path to your SSL chain file or leave empty in case you have none:

Enter pass phrase for /etc/pki/tls/private/server.key:
Which port will this Vhost listen on? [443] 

Please select one of the following options [0]:
0. All web interfaces 
1. Kaltura Management Console [KMC], Hosted Apps, HTML5 lib and ClipApp
2. KAC - Kaltura Admin Console
0
Enabling Apache config - apps.conf
Enabling Apache config - var.conf
Enabling Apache config - admin.conf


========================================================================================================================
Kaltura install answer file written to /tmp/kaltura_02_04_12_19.ans  -  Please save it!
This answers file can be used to silently-install re-install this machine or deploy other hosts in your cluster.
========================================================================================================================


Stopping httpd:                                            [  OK  ]
Starting httpd: Apache/2.2.15 mod_ssl/2.2.15 (Pass Phrase Dialog)
Some of your private key files are encrypted for security reasons.
In order to read them you have to provide the pass phrases.

Server sslkaltura.croydon.ac.uk:443 (RSA)
Enter pass phrase:

OK: Pass Phrase Dialog successful.
                                                           [  OK  ]
Shutting down monit:                                       [FAILED]
Starting monit: monit: generated unique Monit id 2c41461d5b02d2561537e97ef1d9bd94 and stored to '/root/.monit.id'
Starting monit daemon with http interface at [*:2812]
                                                           [  OK  ]
Running Sphinx config...


kaltura-sphinx-2.2.1-16.x86_64
base-config completed successfully, if you ever want to re-configure your system (e.g. change DB hostname) run the following script:
# rm /opt/kaltura/app/base-config.lock
# /opt/kaltura/bin/kaltura-base-config.sh


Starting monit: Starting monit daemon with http interface at [*:2812]
                                                           [  OK  ]


Configuring your Kaltura DB...


Checking MySQL version..
Ver 5.1.73 found compatible

CREATE USER kaltura;
CREATE USER etl;
CREATE DATABASE kaltura;
CREATE DATABASE kaltura_sphinx_log;
CREATE DATABASE kalturadw;
CREATE DATABASE kalturadw_ds;
CREATE DATABASE kalturadw_bisources;
CREATE DATABASE kalturalog;
Checking connectivity to needed daemons...
Connectivity test passed:)
Cleaning cache..
Populating DB with data.. please wait..
Output for /opt/kaltura/app/deployment/base/scripts/installPlugins.php being logged into /opt/kaltura/log/installPlugins.log 
Output for /opt/kaltura/app/deployment/base/scripts/insertDefaults.php being logged into /opt/kaltura/log/insertDefaults.log 
Output for /opt/kaltura/app/deployment/base/scripts/insertPermissions.php being logged into /opt/kaltura/log/insertPermissions.log 
Output for /opt/kaltura/app/deployment/base/scripts/insertContent.php being logged into /opt/kaltura/log/insertContent.log 
Generating UI confs..
Shutting down monit:                                       [FAILED]
Starting monit: Starting monit daemon with http interface at [*:2812]
                                                           [  OK  ]
Running Batch config...


kaltura-batch-10.7.0-1.noarch
base-config completed successfully, if you ever want to re-configure your system (e.g. change DB hostname) run the following script:
# rm /opt/kaltura/app/base-config.lock
# /opt/kaltura/bin/kaltura-base-config.sh


Reloading httpd: not reloading due to configuration syntax error
                                                           [FAILED]



		Archving logs to /opt/kaltura/log/log_02_04_15_12_23.tar.gz...
ERROR: /opt/kaltura/bin/kaltura-batch-config.sh failed:( You can re-run it when the issue is fixed.

**Comment by acheckley** [comment]
cd /tmp/ contains two answer files:

kaltura_02_04_12_17.ans  kaltura_02_04_12_19.ans

**Comment by KalturaCommunity** [comment]
Yup, just concat the smaller one into the bigger one:)
Each separate step creates its own file so one was created during base and 
the other during front.

Thanks,

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by acheckley** [comment]
Hi Jess, I've emailed over. I'm going to have a look through myself to see if I can spot the error.

**Comment by KalturaCommunity** [comment]
Hey Andrew,

Got it, looking. Please also sign our CLA so we can merge your pull.
Thanks.

May the source be with you,

Jess Portnoy

Join us for the Kaltura Connect Virtual Summits 2015 - Register now!
connect.kaltura.com

**Comment by jessp01** [comment]
Closing this one as @acheckley confirmed it fixes the issue.
I patched the install here:
https://github.com/kaltura/platform-install-packages/commit/8dee0dbddb87ebd510c1b7b7413385e2b184f302

And the next version [10.8.0] should include the merged pull by @acheckley.

**Comment by dannie96** [comment]
_________________
Checking MySQL version..
Ver 5.1.73 found compatible

CREATE USER kaltura;
CREATE USER etl;
CREATE DATABASE kaltura;
CREATE DATABASE kaltura_sphinx_log;
CREATE DATABASE kalturadw;
CREATE DATABASE kalturadw_ds;
CREATE DATABASE kalturadw_bisources;
CREATE DATABASE kalturalog;
Checking connectivity to needed daemons...
Connectivity test passed:)
ERROR: Couldn't make an API request to http://xxxxxx:xxxx/api_v3/index.php?service=system&action=ping.
Please check your setup and then run /opt/kaltura/bin/kaltura-db-config.sh again.
_________________

On configuring All in one Kaltura server Docker container I am getting this error.
I am not able to access either KMC or KAC from the Kaltura Home Page after this.

**Comment by jessp01** [comment]
Hi @dannie96.

Please see https://forum.kaltura.org/t/self-hosted-all-in-one-instance-from-v6-uninstall-to-v13-5-0-1-new-install/8055/13.
Should you have additional questions, please post on the forum.

**Comment by dannie96** [comment]
Hi Jess,
We have configured kaltura all in one server container setup.

After login KMC we tried to upload a sample video using a python client but then internal server error occured

Also we are not able to fetch the details of entries already there in KMC with this client.

The default entries are not playable and metadata is not there.

Regards
Anoob Dani Titus


________________________________

**Comment by dannie96** [comment]
Hi,
I have setup kaltura Docker cluster container
All the 9 containers are running and we have given port mapping as per the information given.
But Empty page is coming when loading port 80.

Any help will be appreciated.

Regards,
Anoob



________________________________
