### ISSUE TITLE
Jupiter 10.21 No longer able to use HTTP AKamai Streaming Player 

### ISSUE THREAD

**Issue by jdubb333** [kaltura/platform-install-packages#477]
I had an older version of 10, and created a custom player for our devices, using HTTP Streaming  (Akamai) worked perfectly. I did a fresh server and install due to dwh and some internal server errors, Jess was a huge help in getting 10.21 working for me. Now however when going through some publishing I am unable to use any of the "streaming" Delivery Types Kaltura Auto, progressive download are the only two that work. During Preview I get unable to play video please check your internet connection, When i copy the embeded code to my front end server I get media not found.
Again the exact same procedures worked perfectly on a previous version, we are doing a POC for the streaming rather than downloading.
1) Please let me know if this is not the correct place to post this 
2) any ideas on how to troubleshoot this?
Thank you for your time.

**Comment by jessp01** [comment]
Hi @jdubb333,

Can you please run:
\# kaltlog
from the server's shell and paste the errors you're seeing while trying to playback?
Also, open your browser's dev tools and check the network and console tabs for errors.
Lastly, what is the output for:
mysql> select * from delivery_profile\G
?
please mask sensitive info when pasting the data of this query.

Thanks,

**Comment by jdubb333** [comment]
Thank you for your quick response....  
KALTLOG
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClientBase.php(414): KalturaClientBase->jsObjectToClientObject(Object(stdClass))
--
2015-10-23 08:38:04 [0.000421] [xxx.xxx.xxx.xxx] [709378998] [39] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00027084350585938 seconds
2015-10-23 08:38:04 [0.000226] [xxx.xxx.xxx.xxx [709378998] [40] [PS2] [DeliveryProfilePeer::getDeliveryByPartner] ERR: exception 'Exception' with message 'Delivery ID can't be determined for partnerId [102] streamer type [hdne

FIREFOX CONSOLE MESSAGES:
102?autoembed=true&entry_id=0_7emwb2ik&playerId=kaltura_player_1445607735&cache_st=1445607735&width…:49 
kWidget: Kaltura HTML5 Version: 2.35.5
a.smil:1 GET http://xxxxxxx.xxx.xxxxxxx.xxx/p/102/sp/10200/playManifest/entryId/0_7emw…Zsa2FsMS5vYnMub3V0YmFjay5jb20vaW5kZXgucGhwL2ttYy9rbWM0I2NvbnRlbnR8bWFuYWdl 404 (Not Found)
a.smil:1 
GET http://xxxxxxx.xxx.xxxxxxx.xxx/p/102/sp/10200/playManifest/entryId/0_7emw…Zsa2FsMS5vYnMub3V0YmFjay5jb20vaW5kZXgucGhwL2ttYy9rbWM0I2NvbnRlbnR8bWFuYWdl 404 (Not Found)
a.smil:1
GET http://xxxxxxx.xxx.xxxxxxx.xxx/p/102/sp/10200/playManifest/entryId/0_7emw…Zsa2FsMS5vYnMub3V0YmFjay5jb20vaW5kZXgucGhwL2ttYy9rbWM0I2NvbnRlbnR8bWFuYWdl 404 (Not Found)
a.smil:1
GET http://xxxxxxx.xxx.xxxxxxx.xxx/p/102/sp/10200/playManifest/entryId/0_7emw…Zsa2FsMS5vYnMub3V0YmFjay5jb20vaW5kZXgucGhwL2ttYy9rbWM0I2NvbnRlbnR8bWFuYWdl 404 (Not Found)

mysql> select * from delivery_profile\G;   ( i think my problem might be with rows 9-11 )

mysql> use kaltura
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from delivery_profile\G;
*************************** 1. row ***************************
             id: 1
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Default HTTP Delivery Profile
           type: 10
    system_name: Default_Akamai_HLS_direct
    description: Default Akamai HLS direct
            url: http://xxxxxxxxxxxxxxxxxxxx
      host_name: xxxxxxxxxxxxxxxxxxxxxx
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: applehttp
     is_default: 1
      parent_id: 0
    custom_data: NULL
       priority: 0
*************************** 2. row ***************************
             id: 2
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Default HTTP Delivery Profile
           type: 14
    system_name: Default HTTP Delivery Profile
    description: Default HTTP Delivery Profile
            url: http://xxxxxxxxxxxxxxxxx
      host_name: xxxxxxxxxxxxxxxxxxxxxxxx
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: http
     is_default: 1
      parent_id: 0
    custom_data: NULL
       priority: 0
*************************** 3. row ***************************
             id: 3
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Default HLS Live Delivery Profile
           type: 1001
    system_name: Default_HLS_Live_Delivery_Profile
    description: Default HLS Live Delivery Profile
            url: NULL
      host_name: NULL
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: applehttp
     is_default: 1
      parent_id: 0
    custom_data: NULL
       priority: 0
*************************** 4. row ***************************
             id: 4
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Default HLS To Multicast Live Delivery Profile
           type: 1006
    system_name: Default_HLS_To_Multicast_Live_Delivery_Profile
    description: Default HLS To Multicast Live Delivery Profile
            url: NULL
      host_name: NULL
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: applehttp_to_mc
     is_default: 1
      parent_id: 0
    custom_data: NULL
       priority: 0
*************************** 5. row ***************************
             id: 301
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Default MPEG-DASH Live Delivery Profile
           type: 1003
    system_name: Default MPEG-DASH Live Delivery Profile
    description: Default MPEG-DASH Live Delivery Profile
            url: NULL
      host_name: NULL
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: mpegdash
     is_default: 1
      parent_id: 0
    custom_data: NULL
       priority: 0
*************************** 6. row ***************************
             id: 302
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Default HD Network Live Delivery Profile
           type: 1002
    system_name: Default_HD_Network_Live_Delivery_Profile
    description: Default HD Network Live Delivery Profile
            url: NULL
      host_name: NULL
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: hdnetworkmanifest
     is_default: 1
      parent_id: 0
    custom_data: NULL
       priority: 0
*************************** 7. row ***************************
             id: 303
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Default HDS Live Delivery Profile
           type: 1002
    system_name: Default_HDS_Live_Delivery_Profile
    description: Default HDS Live Delivery Profile
            url: NULL
      host_name: NULL
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: hds
     is_default: 1
      parent_id: 0
    custom_data: NULL
       priority: 0
*************************** 8. row ***************************
             id: 304
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Default RTMP Live Delivery Profile
           type: 1005
    system_name: Default_RTMP_Live_Delivery_Profile
    description: Default RTMP Live Delivery Profile
            url: NULL
      host_name: NULL
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: rtmp
     is_default: 1
      parent_id: 0
    custom_data: a:1:{s:12:"enforceRtmpe";s:1:"0";}
       priority: 0
*************************** 9. row ***************************
             id: 1001
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Kaltura HLS segmentation
           type: 61
    system_name: Kaltura HLS segmentation
    description: Kaltura HLS segmentation
            url: http://http://xxxxxxxxxxxxxxxxxxx:88/hls
      host_name: http
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: applehttp
     is_default: 1
      parent_id: 0
    custom_data: NULL
       priority: 0
*************************** 10. row ***************************
             id: 1002
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Kaltura HDS segmentation
           type: 63
    system_name: Kaltura HDS segmentation
    description: Kaltura HDS segmentation
            url: http://http://xxxxxxxxxxxxxxxxxxxxxxxxx:88/hds
      host_name: http
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: hdnetworkmanifest
     is_default: 1
      parent_id: 0
    custom_data: NULL
       priority: 0
*************************** 11. row ***************************
             id: 1003
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Kaltura DASH segmentation
           type: 68
    system_name: Kaltura DASH segmentation
    description: Kaltura DASH segmentation
            url: http://http://xxxxxxxxxxxxxxxxxxxxxxxxxxxx:88/dash
      host_name: http
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: mpegdash
     is_default: 1
      parent_id: 0
    custom_data: NULL
       priority: 0
11 rows in set (0.00 sec)

ERROR:
No query specified

mysql>

Here is snippet from the answer file:
Packager from answer file:
VOD_PACKAGER_HOST="http://xxxxxxx.xxx.xxxxxx.xxx"
VOD_PACKAGER_PORT="88"

SERVICE_URL="http://xxxxxxx.xxxx.xxxxx.xxx:80"

I am wondering if i misinterpreted the directions the second time around with the config all:
this is what I answered: (I used my real hostname info)
VOD packager hostname [kalrpm.lcl]: "<http://myhostname.mydomain.com>"
Service URL [http://kalrpm.lcl:80]: "<http://myhostname.mydomain.com:80>"
the rows 9-11 seem to have picked up http as the hostname.... 

Thank you again for your assistance.

**Comment by jessp01** [comment]
Hello,

Sure, happy to help:)
The log seem to be cut off at a very important place:)
[DeliveryProfilePeer::getDeliveryByPartner] ERR: exception 'Exception' with message 'Delivery ID can't be determined for partnerId [102] streamer type [hdne

What is the full type its looking for?
Basically, whatever the type is, there should be a matching record for it in delivery_profile, please also look a bit higher up in the log where you should see the query being made to the delivery_profile table, from there on, it will be easier to understand why its failing.

**Comment by jdubb333** [comment]
oops sorry about that... 


Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClientBase.php(414): KalturaClientBase->jsObjectToClientObject(Object(stdClass))
--
2015-10-23 10:55:54 [0.000413] [xx.xxx.xxx.xx] [1263561459] [39] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00026202201843262 seconds
2015-10-23 10:55:54 [0.000227] [xx.xxx.xxx.xx] [1263561459] [40] [PS2] [DeliveryProfilePeer::getDeliveryByPartner] ERR: exception 'Exception' with message 'Delivery ID can't be determined for partnerId [102] streamer type [hdnetwork] and media protocol [http]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/lib/model/DeliveryProfilePeer.php(235): KalturaLog::err('Delivery ID can...')
--
#19 {main}
2015-10-23 10:55:54 [0.000396] [xx.xxx.xxx.xx] [1263561459] [41] [PS2] [KExternalErrors::dieError] ERR: exception 'Exception' with message 'exiting on error 25 - wrong query attributes, This format is unsupported' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(128): KalturaLog::err('exiting on erro...')

ok, I do not have a partner id 102 in delivery_profile table 
and I only have  streamer type hdnetworkmanifest

**Comment by jdubb333** [comment]
so looking at the delivery settings , 

![image](https://cloud.githubusercontent.com/assets/15221223/10699661/767e2fea-7986-11e5-96b4-d1061c8fa67e.png)
 AKamai_HD  (hdnetwork) is not available to add

**Comment by jessp01** [comment]
Hello,

Can you try using HTTP Streaming (HDS) instead? that should work fine with Akamai as well.

**Comment by jdubb333** [comment]
Hello Jess,

That does not work either, was just sitting down to try and set up an install back to 10.19 , not perfect but at least can get it to stream to a  mobile device (I have a POC meeting Wednesday, so can't show up empty handed)...

You have been very helpful, I was unsuccessful trying to use HTTP HDS as well , if you read all the way down to the bottom look at the entries in  rows 9-11 as well, again any help greatly appreciated
select * from delivery_profile\G;
I get this if I use "non custom player" no media found
![image](https://cloud.githubusercontent.com/assets/15221223/10716559/786a508e-7b13-11e5-9f52-24f3c1e9e60c.png)
All Entries in Kaltlog:

 ~]# kaltlog
#1 {main}
2015-10-25 10:00:01 [1862204537] [updateEntryPlaysViews.php] [global] ERR: exception 'Exception' with message 'Couldn't find entry [0_xu5c14yi]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/dwh/updateEntryPlaysViews.php(19): KalturaLog::err('Couldn't find e...')
#1 {main}
2015-10-25 10:00:01 [1862204537] [updateEntryPlaysViews.php] [global] ERR: exception 'Exception' with message 'Couldn't find entry [0_7emwb2ik]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/dwh/updateEntryPlaysViews.php(19): KalturaLog::err('Couldn't find e...')
--
==> /opt/kaltura/log/batch/kschedulehelper-0-2015-10-25.err.log <==
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Invalid KS "NTkwZDUzMWE0OWVjMGU4MWJiYjI3YjVkYmM5YzNjMTcwNDIyYjlmMXwtMTs7MTQ0ODM4MTk5OTsyOzE0NDU3ODk5OTkuNTg0NTtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==", Error "-1,INVALID_STR"' in /opt/kaltura/app/batch/client/KalturaClientBase.php:821
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClientBase.php(414): KalturaClientBase->jsObjectToClientObject(Object(stdClass))
--
==> /opt/kaltura/log/batch/validatelivemediaservers-0-2015-10-25.err.log <==
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Invalid KS "ZTUwZWRkZmYwMmI1YmI4MjM5MjBjM2E5YjExZmE1OTMyNTFlNWJmNXwtMTs7MTQ0ODM4MTk5NTsyOzE0NDU3ODk5OTUuNTY1MjtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==", Error "-1,INVALID_STR"' in /opt/kaltura/app/batch/client/KalturaClientBase.php:821
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClientBase.php(414): KalturaClientBase->jsObjectToClientObject(Object(stdClass))

IF I try using custom player "IPAD" I get this:
![image](https://cloud.githubusercontent.com/assets/15221223/10716627/6753873c-7b15-11e5-8300-2a86789ddd0a.png)

Kaltlog
don't see any changes:[root@oshflkal1 ~]# kaltlog
#1 {main}
2015-10-25 10:00:01 [1862204537] [updateEntryPlaysViews.php] [global] ERR: exception 'Exception' with message 'Couldn't find entry [0_xu5c14yi]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/dwh/updateEntryPlaysViews.php(19): KalturaLog::err('Couldn't find e...')
#1 {main}
2015-10-25 10:00:01 [1862204537] [updateEntryPlaysViews.php] [global] ERR: exception 'Exception' with message 'Couldn't find entry [0_7emwb2ik]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/dwh/updateEntryPlaysViews.php(19): KalturaLog::err('Couldn't find e...')
--
==> /opt/kaltura/log/batch/kschedulehelper-0-2015-10-25.err.log <==
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Invalid KS "NTkwZDUzMWE0OWVjMGU4MWJiYjI3YjVkYmM5YzNjMTcwNDIyYjlmMXwtMTs7MTQ0ODM4MTk5OTsyOzE0NDU3ODk5OTkuNTg0NTtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==", Error "-1,INVALID_STR"' in /opt/kaltura/app/batch/client/KalturaClientBase.php:821
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClientBase.php(414): KalturaClientBase->jsObjectToClientObject(Object(stdClass))
--
==> /opt/kaltura/log/batch/validatelivemediaservers-0-2015-10-25.err.log <==
PHP Fatal error:  Uncaught exception 'KalturaException' with message 'Invalid KS "ZTUwZWRkZmYwMmI1YmI4MjM5MjBjM2E5YjExZmE1OTMyNTFlNWJmNXwtMTs7MTQ0ODM4MTk5NTsyOzE0NDU3ODk5OTUuNTY1MjtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==", Error "-1,INVALID_STR"' in /opt/kaltura/app/batch/client/KalturaClientBase.php:821
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClientBase.php(414): KalturaClientBase->jsObjectToClientObject(Object(stdClass))

Here is the error from chrome console:

kWidget: Kaltura HTML5 Version: 2.35.5
http/crossdomain.xml:1 GET http://http/crossdomain.xml net::ERR_NAME_NOT_RESOLVED

which brings me back to the entries for delivery profile: rows 9, 10 ,11
*************************** 9. row ***************************
             id: 1001
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Kaltura HLS segmentation
           type: 61
    system_name: Kaltura HLS segmentation
    description: Kaltura HLS segmentation
            url: http://http://fqdnhostname:88/hls
      host_name: http
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: applehttp
     is_default: 1
      parent_id: 0
    custom_data: NULL
       priority: 0
*************************** 10. row ***************************
             id: 1002
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Kaltura HDS segmentation
           type: 63
    system_name: Kaltura HDS segmentation
    description: Kaltura HDS segmentation
            url: http://http://fqdnhostname:88/hds
      host_name: http
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: hdnetworkmanifest
     is_default: 1
      parent_id: 0
    custom_data: NULL
       priority: 0
*************************** 11. row ***************************
             id: 1003
     partner_id: 0
     created_at: 2015-10-21 12:30:03
     updated_at: 2015-10-21 12:30:03
           name: Kaltura DASH segmentation
           type: 68
    system_name: Kaltura DASH segmentation
    description: Kaltura DASH segmentation
            url: http://http://fqdnhostname:88/dash
      host_name: http
     recognizer: NULL
      tokenizer: NULL
         status: 0
media_protocols: NULL
  streamer_type: mpegdash
     is_default: 1
      parent_id: 0
    custom_data: NULL
       priority: 0
11 rows in set (0.00 sec)

if its trying to reach http://http://myhostname
hostname http, that doesn't seem correct.

**Comment by jessp01** [comment]
Hi there,

I will look into it tomorrow morning and keep you posted. Im quite sure we can find and fix in time for your POC:)
BTW, I just released 11.0.0 as stable. Would you mind testing that on a test machine?

Sent by Outlook<http://taps.io/outlookmobile> for Android



On Sun, Oct 25, 2015 at 9:57 AM -0700, "jdubb333" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello Jess,

That does not work either, was just sitting down to try and set up an install back to 10.19 , not perfect but at least can get it to stream to a mobile device (I have a POC meeting Wednesday, so can't show up empty handed)...

You have been very helpful, I was unsuccessful trying to use HTTP HDS as well , if you read all the way down to the bottom look at the entries in rows 9-11 as well, again any help greatly appreciated
select * from delivery_profile\G;
I get this if I use "non custom player" no media found
[image]<https://cloud.githubusercontent.com/assets/15221223/10716559/786a508e-7b13-11e5-9f52-24f3c1e9e60c.png>
All Entries in Kaltlog:

~]# kaltlog
#1<https://github.com/kaltura/platform-install-packages/issues/1> {main}
2015-10-25 10:00:01 [1862204537] [updateEntryPlaysViews.php] [global] ERR: exception 'Exception' with message 'Couldn't find entry [0_xu5c14yi]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/dwh/updateEntryPlaysViews.php(19): KalturaLog::err('Couldn't find e...')
#1<https://github.com/kaltura/platform-install-packages/issues/1> {main}
2015-10-25 10:00:01 [1862204537] [updateEntryPlaysViews.php] [global] ERR: exception 'Exception' with message 'Couldn't find entry [0_7emwb2ik]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:

#0 /opt/kaltura/app/alpha/scripts/dwh/updateEntryPlaysViews.php(19): KalturaLog::err('Couldn't find e...')

==> /opt/kaltura/log/batch/kschedulehelper-0-2015-10-25.err.log <==
PHP Fatal error: Uncaught exception 'KalturaException' with message 'Invalid KS "NTkwZDUzMWE0OWVjMGU4MWJiYjI3YjVkYmM5YzNjMTcwNDIyYjlmMXwtMTs7MTQ0ODM4MTk5OTsyOzE0NDU3ODk5OTkuNTg0NTtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==", Error "-1,INVALID_STR"' in /opt/kaltura/app/batch/client/KalturaClientBase.php:821
Stack trace:

#0 /opt/kaltura/app/batch/client/KalturaClientBase.php(414): KalturaClientBase->jsObjectToClientObject(Object(stdClass))

==> /opt/kaltura/log/batch/validatelivemediaservers-0-2015-10-25.err.log <==
PHP Fatal error: Uncaught exception 'KalturaException' with message 'Invalid KS "ZTUwZWRkZmYwMmI1YmI4MjM5MjBjM2E5YjExZmE1OTMyNTFlNWJmNXwtMTs7MTQ0ODM4MTk5NTsyOzE0NDU3ODk5OTUuNTY1MjtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==", Error "-1,INVALID_STR"' in /opt/kaltura/app/batch/client/KalturaClientBase.php:821
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClientBase.php(414): KalturaClientBase->jsObjectToClientObject(Object(stdClass))

IF I try using custom player "IPAD" I get this:
[image]<https://cloud.githubusercontent.com/assets/15221223/10716627/6753873c-7b15-11e5-8300-2a86789ddd0a.png>

Kaltlog
don't see any changes:[root@oshflkal1 ~]# kaltlog
#1<https://github.com/kaltura/platform-install-packages/issues/1> {main}
2015-10-25 10:00:01 [1862204537] [updateEntryPlaysViews.php] [global] ERR: exception 'Exception' with message 'Couldn't find entry [0_xu5c14yi]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/scripts/dwh/updateEntryPlaysViews.php(19): KalturaLog::err('Couldn't find e...')
#1<https://github.com/kaltura/platform-install-packages/issues/1> {main}
2015-10-25 10:00:01 [1862204537] [updateEntryPlaysViews.php] [global] ERR: exception 'Exception' with message 'Couldn't find entry [0_7emwb2ik]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:

#0 /opt/kaltura/app/alpha/scripts/dwh/updateEntryPlaysViews.php(19): KalturaLog::err('Couldn't find e...')

==> /opt/kaltura/log/batch/kschedulehelper-0-2015-10-25.err.log <==
PHP Fatal error: Uncaught exception 'KalturaException' with message 'Invalid KS "NTkwZDUzMWE0OWVjMGU4MWJiYjI3YjVkYmM5YzNjMTcwNDIyYjlmMXwtMTs7MTQ0ODM4MTk5OTsyOzE0NDU3ODk5OTkuNTg0NTtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==", Error "-1,INVALID_STR"' in /opt/kaltura/app/batch/client/KalturaClientBase.php:821
Stack trace:

#0 /opt/kaltura/app/batch/client/KalturaClientBase.php(414): KalturaClientBase->jsObjectToClientObject(Object(stdClass))

==> /opt/kaltura/log/batch/validatelivemediaservers-0-2015-10-25.err.log <==
PHP Fatal error: Uncaught exception 'KalturaException' with message 'Invalid KS "ZTUwZWRkZmYwMmI1YmI4MjM5MjBjM2E5YjExZmE1OTMyNTFlNWJmNXwtMTs7MTQ0ODM4MTk5NTsyOzE0NDU3ODk5OTUuNTY1MjtiYXRjaFVzZXI7ZGlzYWJsZWVudGl0bGVtZW50Oy0xOw==", Error "-1,INVALID_STR"' in /opt/kaltura/app/batch/client/KalturaClientBase.php:821
Stack trace:
#0 /opt/kaltura/app/batch/client/KalturaClientBase.php(414): KalturaClientBase->jsObjectToClientObject(Object(stdClass))

Here is the error from chrome console:

kWidget: Kaltura HTML5 Version: 2.35.5
http/crossdomain.xml:1 GET http://http/crossdomain.xml net::ERR_NAME_NOT_RESOLVED

which brings me back to the entries for delivery profile: rows 9, 10 ,11
*************************** 9. row ***************************
id: 1001
partner_id: 0
created_at: 2015-10-21 12:30:03
updated_at: 2015-10-21 12:30:03
name: Kaltura HLS segmentation
type: 61
system_name: Kaltura HLS segmentation
description: Kaltura HLS segmentation
url: http://http://fqdnhostname:88/hls
host_name: http
recognizer: NULL
tokenizer: NULL
status: 0
media_protocols: NULL
streamer_type: applehttp
is_default: 1
parent_id: 0
custom_data: NULL
priority: 0
*************************** 10. row ***************************
id: 1002
partner_id: 0
created_at: 2015-10-21 12:30:03
updated_at: 2015-10-21 12:30:03
name: Kaltura HDS segmentation
type: 63
system_name: Kaltura HDS segmentation
description: Kaltura HDS segmentation
url: http://http://fqdnhostname:88/hds
host_name: http
recognizer: NULL
tokenizer: NULL
status: 0
media_protocols: NULL
streamer_type: hdnetworkmanifest
is_default: 1
parent_id: 0
custom_data: NULL
priority: 0
*************************** 11. row ***************************
id: 1003
partner_id: 0
created_at: 2015-10-21 12:30:03
updated_at: 2015-10-21 12:30:03
name: Kaltura DASH segmentation
type: 68
system_name: Kaltura DASH segmentation
description: Kaltura DASH segmentation
url: http://http://fqdnhostname:88/dash
host_name: http
recognizer: NULL
tokenizer: NULL
status: 0
media_protocols: NULL
streamer_type: mpegdash
is_default: 1
parent_id: 0
custom_data: NULL
priority: 0
11 rows in set (0.00 sec)

if its trying to reach http://http://myhostname
hostname http, that doesn't seem correct.

-

**Comment by jdubb333** [comment]
Thank you, and yes I will, will let you know the outcome, thanks again.

**Comment by jdubb333** [comment]
11.0 install attempt, maybe hasn't made it to my mirrors yet? 404 not found
included kaltura.repo contents as well, will try again in the morning, thank you
 # rpm -ihv http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
Retrieving http://installrepo.kaltura.org/releases/kaltura-release.noarch.rpm
Preparing...                ########################################### [100%]
   1:kaltura-release        ########################################### [100%]
#

# yum install kaltura-server
Loaded plugins: fastestmirror
Setting up Install Process
Determining fastest mirrors
 * base: centos.mirror.constant.com
 * extras: mirror.cc.columbia.edu
 * updates: mirror.linux.duke.edu
Kaltura                                                  | 2.9 kB     00:00
http://installrepo.kaltura.org/releases/latest/RPMS/x86_64/repodata/2df06b7dcc103b3091f223f62ef774fae5bba533054f449a53541052fcc4ba8a-primary.sqlite.bz2: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
http://installrepo.kaltura.org/releases/latest/RPMS/x86_64/repodata/2df06b7dcc103b3091f223f62ef774fae5bba533054f449a53541052fcc4ba8a-primary.sqlite.bz2: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
Error: failure: repodata/2df06b7dcc103b3091f223f62ef774fae5bba533054f449a53541052fcc4ba8a-primary.sqlite.bz2 from Kaltura: [Errno 256] No more mirrors to try.
[root@oshflv01 etc]#

 etc]# more /etc/yum.repos.d/kaltura.repo
[Kaltura]
name = Kaltura Server
baseurl = http://installrepo.kaltura.org/releases/latest/RPMS/$basearch/
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1

[Kaltura-noarch]
name = Kaltura Server arch independent
baseurl = http://installrepo.kaltura.org/releases/latest/RPMS/noarch
gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
gpgcheck = 1
enabled = 1

# we currently do not have the nightly so commented. We do have plans to add tha
t.
#[Kaltura-testing]
#name = Kaltura Server arch independent
#baseurl = http://installrepo.kaltura.org/releases/nightly/RPMS/$basearch/
#gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
#gpgcheck = 1
#enabled = 0

#[Kaltura-testing-noarch]
#name = Kaltura Server arch independent
#baseurl = http://installrepo.kaltura.org/releases/nightly/RPMS/noarch
#gpgkey = http://installrepo.kaltura.org/releases/RPM-GPG-KEY-kaltura
#gpgcheck = 1
#enabled = 0

**Comment by jessp01** [comment]
Hello,

Yeah, we're using Cloudfront as CDN and sometimes it takes a little while for all edges to be updated.
Please try now and if you're still having issues, replace installrepo.kaltura.org with installrepo.origin.kaltura.org and retry.

But let me know, cause it should all be fully synced by now.

Thanks,

**Comment by jdubb333** [comment]
8:28 EST still receiving PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
I will try the suggested URL 
Thank you

**Comment by jdubb333** [comment]
Hello Jess,

11.0 No streaming working on mobile devices iphones/ipads

HTTP Streaming HDS plays within the preview and embed, and on website (pc) but not on mobile devices, see the thumbnail, and when hit play just get the spinning and play button appears again, if you press that back to thumbnail. have pics if needed. I have verified transcode properties for mobile complete.

Akamai not working: During preview and embed An error was experienced when playing the video , Please check your internet connection and try again:

Errors from browser:
GET http://oshflv01.obs.outback.com/p/101/sp/10100/playManifest/entryId/0_kzyjq…=&playSessionId=d5d3af6d-69a9-cce1-abbf-3e6f5cf22d29&clientTag=html5:v2.36 404 (Not Found)
a.smil:1 
GET http://oshflv01.obs.outback.com/p/101/sp/10100/playManifest/entryId/0_kzyjq…=&playSessionId=d5d3af6d-69a9-cce1-abbf-3e6f5cf22d29&clientTag=html5:v2.36 404 (Not Found)

Kaltlog:

2015-10-26 09:50:25 [0.000157] [10.254.148.245] [1627047278] [51] [API] [SphinxCriteria->applyFilters] DEBUG: Add sort field[entry.CREATED_AT] copy from [entry.CREATED_AT ASC]
2015-10-26 09:50:25 [0.005002] [10.254.148.245] [1627047278] [52] [API] [DbManager::connectFallbackLogic] ERR: exception 'Exception' with message 'failed to connect to sphinx2' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/db/DbManager.php(279): KalturaLog::err('failed to conne...')
--
2015-10-26 09:51:00 [0.001664] [10.254.41.12] [991510153] [37] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00026607513427734 seconds
2015-10-26 09:51:00 [0.000322] [10.254.41.12] [991510153] [38] [PS2] [DeliveryProfilePeer::getDeliveryByPartner] ERR: exception 'Exception' with message 'Delivery ID can't be determined for partnerId [101] streamer type [hdnetwork] and media protocol [http]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/lib/model/DeliveryProfilePeer.php(235): KalturaLog::err('Delivery ID can...')
--
#19 {main}
2015-10-26 09:51:00 [0.000438] [10.254.41.12] [991510153] [39] [PS2] [KExternalErrors::dieError] ERR: exception 'Exception' with message 'exiting on error 25 - wrong query attributes, This format is unsupported' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(128): KalturaLog::err('exiting on erro...')
--
2015-10-26 09:54:28 [0.000477] [10.254.41.12] [1874400182] [37] [PS2] [KalturaStatement->execute] DEBUG: Sql took - 0.00031399726867676 seconds
2015-10-26 09:54:28 [0.000238] [10.254.41.12] [1874400182] [38] [PS2] [DeliveryProfilePeer::getDeliveryByPartner] ERR: exception 'Exception' with message 'Delivery ID can't be determined for partnerId [101] streamer type [hdnetwork] and media protocol [http]' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/lib/model/DeliveryProfilePeer.php(235): KalturaLog::err('Delivery ID can...')
--
#19 {main}
2015-10-26 09:54:28 [0.000291] [10.254.41.12] [1874400182] [39] [PS2] [KExternalErrors::dieError] ERR: exception 'Exception' with message 'exiting on error 25 - wrong query attributes, This format is unsupported' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/KExternalErrors.class.php(128): KalturaLog::err('exiting on erro...')
--
2015-10-26 09:55:35 [0.000156] [10.254.148.245] [856695018] [51] [API] [SphinxCriteria->applyFilters] DEBUG: Add sort field[entry.CREATED_AT] copy from [entry.CREATED_AT ASC]
2015-10-26 09:55:35 [0.001150] [10.254.148.245] [856695018] [52] [API] [DbManager::connectFallbackLogic] ERR: exception 'Exception' with message 'failed to connect to sphinx2' in /opt/kaltura/app/infra/log/KalturaLog.php:83
Stack trace:
#0 /opt/kaltura/app/alpha/apps/kaltura/lib/db/DbManager.php(279): KalturaLog::err('failed to conne...')

**Comment by jdubb333** [comment]
I ended up installing 10.19 again and HTTP Streaming (HDS) works great.. not sure if that information helps ... 

I will circle back to 11.0 in a bit to see if resolved, thank you.
